name       : kirigami-addons
version    : 0.7.0
release    : 1
source     :
    - https://download.kde.org/stable/kirigami-addons/kirigami-addons-0.7.0.tar.xz : 0132a58b150229544a61e17e792c48cfc6daa03a8be9c7acd873a6c30d283df7
license    : GPL-2.0-or-later
component  : programming.library
summary    : Convergent visual components ("widgets") for Kirigami-based applications
description: |
    A set of "widgets" i.e visual end user components along with a code to support them. Components are usable by both touch and desktop experiences providing a native experience on both, and look native with any QQC2 style (qqc2-desktop-theme, Material or Plasma)
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5QuickControls2)
    - extra-cmake-modules
    - ki18n-devel
    - kirigami2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
